"""empty message

Revision ID: affdea0e2edd
Revises: e333d0326181
Create Date: 2021-01-18 02:29:58.593628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affdea0e2edd'
down_revision = 'e333d0326181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
